### ISSUE TITLE
Tapping quick does not register as tap. And Pinch/Twist constantly switching to Multiple finger drag.

### ISSUE THREAD

**Issue by golddotasksquestions** [Federico-Ciuffardi/Godot-Touch-Input-Manager#11]
This addon looked incredible promising, and I would have loved to use it in my Android projects, but upon first testing it seemed very laggy and buggy.

To test my impression, I added a simple counter to check if all my taps are registered:
```swift
extends Node2D

onready var label = $Label
onready var label2 = $Label2


var tap_counter = 0

func _input(event):
	if (event is InputEventMultiScreenDrag or
		event is InputEventSingleScreenDrag or
		event is InputEventScreenPinch or
		event is InputEventScreenTwist or
		event is InputEventSingleScreenTap or
		event is InputEventSingleScreenTouch):
			label.text = event.as_text()
	if event is InputEventMultiScreenDrag:
		label2.text = "Multiple finger drag"
	elif event is InputEventSingleScreenDrag:
		label2.text = "Single finger drag"
	elif event is InputEventScreenPinch:
		label2.text = "Pinch"
	elif event is InputEventScreenTwist:
		label2.text = "Twist"
	elif event is InputEventSingleScreenTap:
		tap_counter +=1
		label2.text = "Single finger tap "+ str(tap_counter)
	elif event is InputEventSingleScreenTouch:
		label2.text = "Single finger touch"
```
My impression seemed correct since taps after a certain frequency don't register at all any more.
That's very unfortunate, because the features of this addon would be really amazing if they would work.

Pinch and "Twist" also did not seem reliable at all, constantly switching to "Multiple finger drag"

**Comment by golddotasksquestions** [comment]
Lowering const TOUCH_DELAY_TIME  did not help. I tried 0.01 but then no tabs are registered at all. with 0.1 only some tabs are registered. with 0.05 almost no tabs are registered, it feels very unreliable whatever TOUCH_DELAY_TIME setting I choose.
I could not figure out what you mean with: "You may also consider using ʻInputEventSingleScreenTouchwithpressed = true` for high frequency taps." 
Where would I be using that? What means "using" in this case?

**Comment by Federico-Ciuffardi** [comment]
Ok, maybe some work could be done on the tap event support high frequency taps. Actually, when I implemented the tap event, I didn't think about fast taps.

Either way I advice you to try the alternative I proposed. What I meant was "You may also consider using `InputEventSingleScreenTouch` with `pressed == true` for high frequency taps".  
In this case using means to do something like this:
```
if event is InputEventSingleScreenTouch and event.pressed:
```
instead of this:
```
if event is InputEventSingleScreenTap:
```

Please try that and let me know if it worked.

And did setting thresholds solve your problems with Pinch and Twist?

**Comment by harry-peirse** [comment]
Hi! I'm trying out this plugin and finding it incredibly useful. I am finding that the default 200 millisecond delay for tap events makes the game feel quite unresponsive as the delay between the tap and the action is recognisable, but when I shorten it there's a risk of not capturing the taps of course. I'm going to play around with InputEventSingleScreenTouch to see if that can improve things, but I just wanted to comment here as well so you're aware there's some needs not covered. If I find a nice solution I'll post it and potentially look into a merge request if you're interested.
Thanks for a great plugin!

**Comment by Federico-Ciuffardi** [comment]
Hi @harry-peirse, your comment on the delay made me think about how and when I was detecting a tap, and also what the definition of tap is.

I just changed the implementation (on [this](https://github.com/Federico-Ciuffardi/Godot-Touch-Input-Manager/tree/tap-rework) branch) so that instead of waiting for the end of the timer, it waits at most for that time, and if it detects that the touch is released before a the timer end a tap event is emitted.

This solves both the delay you mentioned and the detection of fast taps that @golddotasksquestions mentioned.

I wonder if it is correct to have a time limit for the detection of a tap. Perhaps it is better to remove the time limit and add a check that the press and release position do not differ by more than a certain threshold.

Please check if the new implementation suits your needs and tell me your opinion on what I talk about in the paragraph, if you can.

Thanks!

**Comment by harry-peirse** [comment]
Hey, thanks a lot for doing that so quickly - it works great!
I think it's good to have the threshold (configurable ideally) as you may want to recognise a hold without moving separately from a tap. The idea of a separate threshold for position differences would be nice for separating a hold event from drag however. Holding to bring up a context menu is a good use case (one I have actually)

**Comment by Federico-Ciuffardi** [comment]
Thank you for your feedback! I will merge the changes soon and release a new version.

**Comment by golddotasksquestions** [comment]
Personally I would expect the same behaviour as Input static class:

tab = Input.is_action_just pressed()
tab_hold = Input.is_action_pressed()
